// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyeynvboclhmuboywzbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5ZXludmJvY2xobXVib3l3emJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTUxODEsImV4cCI6MjA2NjQzMTE4MX0.ZP1DLhnNBwn-jBuu-IZm0PoEaNPv3RuY28UZ2zeBCKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);